services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: helios_backend:${HELIOS_BACKEND_VERSION:-latest}
    restart: always
    env_file:
      - path: .env
        required: true
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully

  taskiq-worker:
    <<: *main_app
    labels: []
    command:
      - taskiq
      - worker
      - helios_backend.tkq:broker

  taskiq-scheduler:
    <<: *main_app
    labels: []
    command:
      - taskiq
      - scheduler
      - helios_backend.tkq:scheduler
      - --update-interval
      - "1"
      - --loop-interval
      - "1"

  telegram-bot:
    <<: *main_app
    labels: []
    command:
      - python
      - -m
      - helios_backend.bot

  db:
    image: postgres:18.1-bookworm
    hostname: helios_backend-db
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${HELIOS_BACKEND_DB_USER:-helios_backend}
      POSTGRES_PASSWORD: ${HELIOS_BACKEND_DB_PASS:-helios_backend}
      POSTGRES_DB: ${HELIOS_BACKEND_DB_BASE:-helios_backend}
    volumes:
      - helios_backend-db-data:/var/lib/postgresql
    restart: always
    healthcheck:
      test: pg_isready -U ${HELIOS_BACKEND_DB_USER:-helios_backend}
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    <<: *main_app
    restart: "no"
    command: aerich upgrade
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:8.4.0
    hostname: "helios_backend-redis"
    restart: always
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

volumes:
  helios_backend-db-data:
    name: helios_backend-db-data
