services:
  api:
    ports:
      # Exposes application port.
      - "8000:8000"
    build:
      context: .
    volumes:
      # Adds current directory as volume.
      - .:/app/src/

  taskiq-worker:
    volumes:
      # Adds current directory as volume.
      - .:/app/src/
    command:
      - taskiq
      - worker
      - helios_backend.tkq:broker
      - --reload

  taskiq-scheduler:
    volumes:
      - .:/app/src/
    command:
      - taskiq
      - scheduler
      - helios_backend.tkq:scheduler

  telegram-bot:
    volumes:
      - .:/app/src/
    command:
      - python
      - -m
      - helios_backend.bot

  db:
    ports:
      - "${HELIOS_BACKEND_DB_EXTERNAL_PORT:-5432}:5432"
